version: '3'

services: 
  postgres:
    image: "postgres:latest"
    ports: 
      - "5432"
  redis:
    image: "redis:6.2-alpine"
    ports: 
      - "6379"
  articles:
    depends_on: 
      - postgres
      - redis
    build: .
    environment: 
      - PORT=3001
      - NODE_ENV=production
      - DB_USERNAME_DEVELOPMENT=postgres 
      - DB_PASSWORD_DEVELOPMENT=postgres 
      - DB_NAME_DEVELOPMENT=article_staging 
      - DB_HOST_DEVELOPMENT=postgres
      - DB_USERNAME_PRODUCTION=postgres 
      - DB_PASSWORD_PRODUCTION=postgres 
      - DB_NAME_PRODUCTION=article_production 
      - DB_HOST_PRODUCTION=postgres 
      - DB_DIALECT_PRODUCTION=postgres 
      - DB_USERNAME_TEST=postgres 
      - DB_PASSWORD_TEST=postgres 
      - DB_NAME_TEST=article_staging_test 
      - DB_HOST_TEST=postgres 
      - DB_DIALECT_TEST=postgres 
      - ARTICLE_KEY_REDIS=article 
      - REDIS_HOST=redis
    ports: 
      - "3001:3001"
      - "3000:3000"